language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
- npm i -g gatsby
- npm i
script:
- npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_d31eea6005f9_key -iv $encrypted_d31eea6005f9_iv
  -in deploy_key.enc -out ./deploy_key -d
